### PR TITLE
#15: Call to fpp preprocess functions on parent themes.

### LINKED ISSUE #15: Call preprocess in parent themes for FPPs.
## Movitation
Imagine a project where you share your codebase for multiple instalations.

In that project, you decide to use a parent theme and a subtheme for every instalation were you can customize the appearence for that specific installation.

In that case may be necessary to execute some preprocess for all subthemes in order to avoid redundant code.

### PR DESCRIPTION
**Pull request by alvar0hurtad0**
closes #15

### CODE REVIEW

**Comment by d34dman** [comment]
This is a very good idea. 

I see the current logic is to check if the preprocess function exists in base theme "ONLY" if it is not defined in the current theme. 

How about we refine the logic as such,

Start checking if the preprocess function exists in the active theme array in the order of inheritance and execute them right away.

Since the variable is modified by reference, It shouldn't cause any issue.

Eg.
Scenario, 
ALPHA is the base theme of BETA is the base theme of GAMMA

so order of calls would be,
```
ALPHA__preprocess_fieldable_panels_pane_cta($vars);
BETA__preprocess_fieldable_panels_pane_cta($vars);
GAMMA__preprocess_fieldable_panels_pane_cta($vars);
```
This way, GAMMA can decide to just include some extra preprocessing logic on `cta` if needed. This will be very similar to how preprocessing functions works in Drupal.

What do you think?

**Comment by alvar0hurtad0** [comment]
Makes sense to me @d34dman, I'm doing the implementation. I'll add a new commit in a few minutes.

**Comment by alvar0hurtad0** [comment]
@d34dman Please find the new code, I believe that it does the expected.

**Comment by d34dman** [comment]
Thanks for your contribution :) merged!

**Pull request merged**
